#!/bin/bash

while :
do
	~/steam/l4d2/srcds_run -console -game left4dead2 -port 27017 +map c5m1_waterfront +servercfgfile "server3.cfg" +log off -insecure
	echo -e "Hit Ctrl+C in 3 seconds to prevent restart\n"
	sleep 3
done
