#!/bin/bash

while :
do
	~/steam/l4d2/srcds_run -console -game left4dead2 -port 27016 +map c3m1_plankcountry +log off +servercfgfile "server2.cfg" -insecure #-nomaster
	echo -e "Hit Ctrl+C in 3 seconds to prevent restart\n"
	sleep 3
done
